import streamlit as st
import pandas as pd
import openpyxl
from ortools.sat.python import cp_model

GRADES = ["G7", "G8", "G9"]
DAYS = range(5)
PERIODS = range(8)

SUBJECTS = [
    "Mathematics", "English", "CRE", "Kiswahili",
        "Social Studies", "Science", "Pre-Tech",
            "Agriculture", "Creative Arts"
            ]

            # ---------------- LOAD EXCEL ----------------
            def load_excel(file):
                df = pd.read_excel(file, sheet_name="Data")

                    req = {}
                        teacher = {}

                            for _, r in df.iterrows():
                                    g, s, t, p = r["Grade"], r["Subject"], r["Teacher"], r["Periods"]

                                            req.setdefault(g, {})
                                                    req[g][s] = int(p)
                                                            teacher[(s, g)] = int(t)

                                                                return req, teacher


                                                                # ---------------- MODEL ----------------
                                                                def build(req, teacher_map):
                                                                    model = cp_model.CpModel()
                                                                        x = {}

                                                                            for g in GRADES:
                                                                                    for d in DAYS:
                                                                                                for p in PERIODS:
                                                                                                                for s in SUBJECTS:
                                                                                                                                    x[(g,d,p,s)] = model.NewBoolVar(f"{g}{d}{p}{s}")

                                                                                                                                        for g in GRADES:
                                                                                                                                                for d in DAYS:
                                                                                                                                                            for p in PERIODS:
                                                                                                                                                                            model.Add(sum(x[(g,d,p,s)] for s in SUBJECTS) == 1)

                                                                                                                                                                                for g in GRADES:
                                                                                                                                                                                        for s in req[g]:
                                                                                                                                                                                                    model.Add(
                                                                                                                                                                                                                    sum(x[(g,d,p,s)] for d in DAYS for p in PERIODS)
                                                                                                                                                                                                                                    == req[g][s]
                                                                                                                                                                                                                                                )

                                                                                                                                                                                                                                                    # teacher conflict
                                                                                                                                                                                                                                                        teachers = set(teacher_map.values())

                                                                                                                                                                                                                                                            for t in teachers:
                                                                                                                                                                                                                                                                    for d in DAYS:
                                                                                                                                                                                                                                                                                for p in PERIODS:
                                                                                                                                                                                                                                                                                                model.Add(
                                                                                                                                                                                                                                                                                                                    sum(
                                                                                                                                                                                                                                                                                                                                            x[(g,d,p,s)]
                                                                                                                                                                                                                                                                                                                                                                    for g in GRADES
                                                                                                                                                                                                                                                                                                                                                                                            for s in SUBJECTS
                                                                                                                                                                                                                                                                                                                                                                                                                    if teacher_map.get((s,g)) == t
                                                                                                                                                                                                                                                                                                                                                                                                                                        ) <= 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                        )

                                                                                                                                                                                                                                                                                                                                                                                                                                                            # math & english before lunch
                                                                                                                                                                                                                                                                                                                                                                                                                                                                for g in GRADES:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for d in DAYS:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for p in range(6,8):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    model.Add(x[(g,d,p,"Mathematics")] == 0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    model.Add(x[(g,d,p,"English")] == 0)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return model, x


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # ---------------- SOLVER ----------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def solve(model):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            solver = cp_model.CpSolver()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                solver.parameters.max_time_in_seconds = 20
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    status = solver.Solve(model)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return solver, status


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # ---------------- EXPORT ----------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def export(solver, x):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            output = {}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for g in GRADES:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        table = []

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for d in DAYS:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            row = []
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for p in PERIODS:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        val = ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for s in SUBJECTS:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if solver.Value(x[(g,d,p,s)]) == 1:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    val = s
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            break
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            row.append(val)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        table.append(row)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                output[g] = pd.DataFrame(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            table,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        columns=[f"P{i+1}" for i in range(8)]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return output


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # ---------------- UI ----------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    st.title("📘 School Timetable Generator (AI Optimized)")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    uploaded = st.file_uploader("Upload Excel File", type=["xlsx"])

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if uploaded:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        req, teacher = load_excel(uploaded)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if st.button("Generate Timetable"):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    model, x = build(req, teacher)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            solver, status = solve(model)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if status in [cp_model.OPTIMAL, cp_model.FEASIBLE]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                result = export(solver, x)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            st.success("Timetable generated successfully!")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for g, df in result.items():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        st.subheader(g)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        st.dataframe(df)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            st.error("No valid timetable found")